<project name="MeetingPlanner" default="run-tests" basedir=".">
    <property name="src.main" value="src/main/java"/>
    <property name="src.test" value="src/test/java"/>
    <property name="build" value="build"/>
    <property name="docs" value="doc"/>
    <property name="lib" value="lib"/>
    <property name="coverage.dir" value="coverage"/>

    <path id="jacoco.classpath">
        <fileset dir="${lib}">
            <include name="jacocoant.jar"/>
        </fileset>
    </path>

    <taskdef uri="antlib:org.jacoco.ant"
             resource="org/jacoco/ant/antlib.xml"
             classpathref="jacoco.classpath" />

    <target name="clean">
        <delete dir="${build}"/>
        <delete dir="${docs}"/>
        <delete dir="${coverage.dir}"/>
    </target>

    <target name="compile" depends="clean">
        <mkdir dir="${build}/main"/>
        <javac srcdir="${src.main}" destdir="${build}/main" includeantruntime="false">
            <classpath>
                <fileset dir="${lib}">
                    <include name="**/*.jar"/>
                </fileset>
            </classpath>
        </javac>
    </target>

    <target name="compile-tests" depends="compile">
        <mkdir dir="${build}/test"/>
        <javac srcdir="${src.test}" destdir="${build}/test" includeantruntime="false">
            <classpath>
                <pathelement path="${build}/main"/>
                <fileset dir="${lib}">
                    <include name="**/*.jar"/>
                </fileset>
            </classpath>
        </javac>
    </target>

    <target name="javadoc" depends="compile">
        <mkdir dir="${docs}"/>
        <javadoc sourcepath="${src.main}" destdir="${docs}" author="true" version="true" use="true"
                 windowtitle="MeetingPlanner API"/>
    </target>

    <target name="run-tests" depends="compile-tests">
        <junit printsummary="yes" haltonfailure="false" fork="true">
            <classpath>
                <pathelement path="${build}/main"/>
                <pathelement path="${build}/test"/>
                <fileset dir="${lib}">
                    <include name="**/*.jar"/>
                </fileset>
            </classpath>
            <batchtest>
                <fileset dir="${src.test}">
                    <include name="**/*Test.java"/>
                </fileset>
            </batchtest>
        </junit>
    </target>

    <target name="coverage" depends="compile-tests" description="Run tests with JaCoCo and generate HTML/XML reports">
        <mkdir dir="${coverage.dir}"/>

        <jacoco:coverage destfile="${coverage.dir}/jacoco.exec" xmlns:jacoco="antlib:org.jacoco.ant">
            <junit printsummary="on" haltonfailure="false" fork="true">
                <classpath>
                    <pathelement path="${build}/main"/>
                    <pathelement path="${build}/test"/>
                    <fileset dir="${lib}">
                        <include name="**/*.jar"/>
                    </fileset>
                </classpath>
                <formatter type="plain"/>
                <batchtest>
                    <fileset dir="${src.test}">
                        <include name="**/*Test.java"/>
                    </fileset>
                </batchtest>
            </junit>
        </jacoco:coverage>

        <jacoco:report xmlns:jacoco="antlib:org.jacoco.ant">
            <executiondata>
                <file file="${coverage.dir}/jacoco.exec"/>
            </executiondata>
            <structure name="MeetingPlanner">
                <classfiles>
                    <fileset dir="${build}/main">
                        <exclude name="**/PlannerInterface.class"/>
                        <exclude name="**/TimeConflictException.class"/>
                    </fileset>
                </classfiles>
                <sourcefiles encoding="UTF-8">
                    <fileset dir="${src.main}"/>
                </sourcefiles>
            </structure>
            <html destdir="${coverage.dir}/report"/>
            <xml  destfile="${coverage.dir}/report/jacoco.xml"/>
            <csv  destfile="${coverage.dir}/report/jacoco.csv"/>
        </jacoco:report>
    </target>
</project>